name = "MaskedArrays"
uuid = "e3e6debb-e142-42bc-8e83-ba8646d1d252"
authors = ["Kyle Daruwalla <daruwalla.k.public@icloud.com>"]
version = "0.2.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"

[compat]
GPUArrays = "8"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
