name = "MaskedArrays"
uuid = "e3e6debb-e142-42bc-8e83-ba8646d1d252"
authors = ["Kyle Daruwalla <daruwalla.k.public@icloud.com>"]
version = "0.1.1"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
