name = "MaskedArrays"
uuid = "e3e6debb-e142-42bc-8e83-ba8646d1d252"
authors = ["Kyle Daruwalla <daruwalla.k.public@icloud.com>"]
version = "0.1.0"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
